### ISSUE TITLE
iOS 12.5.7. app crash at start

### ISSUE THREAD

**Issue by Samueleuf** [whereby/ios-sdk#11]
hello, 
we have problem with old device with iOS 12.5.7. app crash at start.
I know that this iOS version is not supported in fact the functionality is disabled in app but app must starts.
I attach the log.
before there were not problem
thanks

[Buddyfit-2023-02-22-162608.txt](https://github.com/whereby/ios-sdk/files/10823073/Buddyfit-2023-02-22-162608.txt)

**Comment by remi-quinto** [comment]
> hello, we have problem with old device with iOS 12.5.7. app crash at start. I know that this iOS version is not supported in fact the functionality is disabled in app but app must starts. I attach the log. before there were not problem thanks
> 
> [Buddyfit-2023-02-22-162608.txt](https://github.com/whereby/ios-sdk/files/10823073/Buddyfit-2023-02-22-162608.txt)

Hi @Samueleuf and thanks for your feedback. As you mentioned, the SDK is not available for iOS 12.X.
That said, we did not make any change to the SDK since the last release in August 2022. Did the crash start happening when you updated to the last version of the SDK (0.7.0) ?

Thanks, have a good day. 
Remi.

**Comment by Samueleuf** [comment]
Hi

it seems that the problem is due to last month's update of iOS 12.5.7.

Best regards

Il giorno mer 8 mar 2023 alle 19:19 Remi Quinto ***@***.***>
ha scritto:

**Comment by remi-quinto** [comment]
We won't fix this issue for now as we aim to support earlier versions of iOS only.
